# NUMPY

#### Numpy is a fundamental package for scientific computing in python. It is a python library that provides a Multi Dimensional Array Object(ndarray) and various derived objects such as Masked Arrays or Matrices and an assortment of routines for fast operations on arrays including Mathematical, Logical, shape manipulation, Sorting, Selecting, I/O, Discrete Fourier Transform, Basic Linear Algebra, Statistical Operations, Radom Simulation etc.

#### At the core of the Numpy package is the ndimensional Array object. 

### Why NumPy over Python lists?
##### Python list: [1, 2, 3] stores pointers to Python objects — slow and memory-heavy. NumPy array: stores raw numbers in contiguous memory — up to 50× faster for large datasets.This speed is critical for ML/AI — every tensor in TensorFlow & PyTorch is built on NumPy concepts.

## Numpy Arrays Vs Python Lists

#### Numpy Arrays have a fixed size at creation, unlike Python Lists which grow dynamically. Changing the size of a ndim array will create a new array and delete the original.

#### The elements in a Numpy array are required to be of same data type and thus of the same size in memory.
#### Numpy Arrays facilitate advanced Mathematical and other types of operations on huge amount of data. Such operations are executed efficiently with less code.

In [5]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

### np.array() ---> To create Multidimensional Arrays.

In [7]:
numpy_array = np.array([1,2,3,4,5])
print('1D Array(Vector): ', numpy_array)
print(type(numpy_array))

1D Array(Vector):  [1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
matrix = np.array([[1,2,3], [4,5,6]])
print('2D Array(Matrix): ', matrix)
print(type(matrix))

2D Array(Matrix):  [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [9]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
ThreeDArray = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print('3D Array(Tensor): ', ThreeDArray)

3D Array(Tensor):  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
ThreeDArray

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### dtype parameter ---> helps to decide size of the data we are going to store inside our array

In [12]:
np.array([1,2,3,4], dtype=np.int32) # np.int32(32bit), np.int64, np.float32, np.float64, int, float

array([1, 2, 3, 4], dtype=int32)

In [13]:
np.array([5,6,7,8], dtype=bool)

array([ True,  True,  True,  True])

In [14]:
# nbytes -> Total memory consumed (in bytes)
# itemsize -> Bytes per individual element
# size -> Total number of elements
arr = np.array([5,6,7,8], dtype=np.int32)
print(arr.itemsize)
print(arr.size)
print(arr.nbytes) # nbytes = itemsize * size
# 1 Byte = 8 bits; 32 bits = 32/8 bytes = 4 bytes. 
# So, 4 eles = 4*4 = 16 bytes

4
4
16


### arange() --> helps us out in providing values over a certain range. Equivalent to range() function in lists.

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,17) # 1 to 16

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [17]:
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### reshape() ---> changes the dimensions (shape) of an array without altering its underlying data. can be used in conjunction with arange()

In [18]:
arange_data = np.arange(1, 17)

In [19]:
arange_data.reshape(4,4) # 4 rows, 4 cols (rows*cols must be shape of the array)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
arange_data.reshape(2, 2, 4) # 3D: 2×2×4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [52]:
new_arange = np.arange(2,17,2)
new_arange

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [55]:
print(new_arange.size) # Total Elements in the Arrray
print(new_arange.shape) # (Rows, Cols)

8
(8,)


In [61]:
reshaped_array = new_arange.reshape(4,2)
reshaped_array

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [77]:
print(new_arange.shape)
print(reshaped_array.shape)
# axis=0 refers to the rows (the first dimension).
# axis=1 refers to the columns (the second dimension).
print(np.size(reshaped_array, axis=1))

(8,)
(4, 2)
2


### Transpose --> a new matrix formed by swapping the original matrix's rows and columns.Reverses or permutes the axes of an array

In [23]:
m = np.array([[1,2,3],[4,5,6]]) # Transpose: (2,3) → (3,2)
print(m.T)

[[1 4]
 [2 5]
 [3 6]]


### flatten() --> converts a multi-dimensional matrix or array into a one-dimensional copy and prints it

In [25]:
print(m.flatten()) # Always returns 1D copy: [1,2,3,4,5,6]

[1 2 3 4 5 6]


### ravel() --> a function used to flatten a multi-dimensional array into a one-dimensional array. 
#### np.ravel() is that it returns a view of the original array whenever possible, rather than a copy. This makes it highly memory-efficient. However, because it returns a view, modifying elements in the raveled array will directly modify the original array.
### How it is different from flatten():
* ravel() returns a view of the original array, while flatten() returns a completely new copy of the data in memory.
*    ravel(): If you change a value in the flattened array, the original matrix changes too because they share memory.
*    flatten(): If you change a value in the flattened array, the original matrix stays completely safe and unchanged.
* ravel(): Faster and uses less computer memory because it does not duplicate data.
* flatten(): Slower and uses more memory because it has to copy every single item over to a new location.

In [26]:
print(m.ravel())

[1 2 3 4 5 6]


In [30]:
# Create a proper 2x2 matrix
m = np.array([[1, 2], [3, 4]])

# Using ravel (shares memory)
r = m.ravel()
r[0] = 99  # Change first element

print("Original m after ravel change:\n", m) 
# Output shows original changed: [[99  2] [ 3  4]]

# Reset m
m = np.array([[1, 2], [3, 4]])

# Using flatten (makes a copy)
f = m.flatten()
f[0] = 99  # Change first element

print("\nOriginal m after flatten change:\n", m) 
# Output shows original is safe: [[1 2] [3 4]]


Original m after ravel change:
 [[99  2]
 [ 3  4]]

Original m after flatten change:
 [[1 2]
 [3 4]]


### ones() --> makes all elements of array/matrix to be 1. Mainly used to initialize the weight of neurons in neural network architecture.

### zeros() ---> makes all elements of array/matrix to be 0.

In [88]:
np.ones(4)

array([1., 1., 1., 1.])

In [89]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [90]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
np.zeros((4,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### random() --> helps us to generate any random values from 0 to 1 inside our matrix

In [95]:
np.random.random()

0.6876620553592011

In [93]:
np.random.random((3,4))

array([[0.74300515, 0.18342359, 0.29131495, 0.47779433],
       [0.92178484, 0.9666292 , 0.75427373, 0.70924313],
       [0.62639041, 0.51997412, 0.85765409, 0.88270058]])

### identity() --> helps us out in creating the matrix as an identity matrix.
#### Note: Identity Matrix = Square Matrix where all diagonal values are 1. 
#### Property of Square Matrix: No.of Rows = No.of Cols

In [102]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### linspace() --> It makes sure that every value within the given range is going to have similar distance from each other (same dist from left, right).

#### np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
#### Core Parameters: 
*  start: The starting value of the sequence.
*  stop: The end value of the sequence.
*  num (Optional): The number of samples to generate. The default is 50.
*  endpoint (Optional): If True (default), the stop value is included as the last element. If False, it is excluded.
*  retstep (Optional): If set to True, the function returns both the array and the calculated step size as a tuple (array, step).
*  dtype (Optional): The data type of the output array (e.g., float, int).

In [113]:
np.linspace(-10, 10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [114]:
np.linspace(-10, 10, 10, False, True)

(array([-10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.]),
 np.float64(2.0))

# Attributes:

### ndim -> ndim stands for n dimension. Gives Dimension of given array

In [117]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [118]:
arr.ndim # 1-D Array

1

In [128]:
threed_array = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
threed_array

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [129]:
threed_array.ndim

3

### shape() --> gives idea about no.of rows, cols in our dataset

In [131]:
shape_array = np.array([[1,2,3],[4,5,6]])
shape_array.shape # 2 Rows, 3 Cols

(2, 3)

In [132]:
ThreeD_shape = np.array([[[1,2], [3,4]], [[1,2], [3,4]]])
ThreeD_shape

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [ ]:
ThreeD_shape.shape # 2 Rows, 2 cols, z axis(we have two 2-D plots)

(2, 2, 2)

### size --> Total No.of Elements in our Dataset/Array.

In [135]:
np.arange(5,57).size

52

### itemsize --> size of each single element in bytes

In [136]:
np.array([[1,2], [3,4], [5,6]]).itemsize

8

In [138]:
np.array([[1,2], [3,4], [5,6]], dtype=np.int32).itemsize

4

### dypte --> Type of every element inside our array

In [143]:
m = np.array([[1,2,3], [4,5,6]])

In [144]:
m.dtype

dtype('int64')

In [152]:
print(m[1, 2]) # row 1, col 2
print(m[0, :]) # [1, 2, 3] — entire first row
print(m[:, 1]) # [2, 5] — entire second column
print(m[0:2, 1:3]) # [[2,3],[5,6]] — submatrix
# m[row_slice, column_slice] --> Takes 1st 2 rows, 2nd & 3rd col elements
# # Flip Columns Horizontally (Left to Right)
print(m[:, ::-1]) # Keeps rows normal, reverse the columns
# Flip Rows Vertically (Upside Down)
print(m[::-1, :])
# Flip Both (Completely Inverted)
print(m[::-1, ::-1])

6
[1 2 3]
[2 5]
[[2 3]
 [5 6]]
[[3 2 1]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]
[[6 5 4]
 [3 2 1]]


### Mathematical Operations in Numpy